language:
  - cpp
compiler:
  - g++
before_install:
  - sudo apt-get install libboost-dev
  - git clone https://github.com/boostorg/asio.git
  - cd asio/include
  - sudo cp -r boost/ /usr/include
  - echo "Ok"